name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bharatkumarsharma/bootcamp-testing

  publish:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Push the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: bharatkumarsharma/bootcamp-testing
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      
      
